# chrome does not work on travis at the moment
# https://github.com/travis-ci/travis-ci/issues/938
# setup saucelabs with sauce connect:
# https://docs.saucelabs.com/ci-integrations/travis-ci/#configure-travis-ci-to-start-sauce-connect
# will work only for pull requests from salad repo branches, not from forks
language: python
env:
  global:
  - secure: NYFGMEkVVvBx8NLGcWnAkieJ11vxT4EVqN/9iQ95IF2XiswtkmUnFFRGyH1KbwaftzbXsg6S1gc79WxR2/EGBJuIHtFVsb8A7r6vedkX3dhcyjITa41uSP5EWANYdl6nsf4/u5oINXoGf/InI6jwqBpRhNV+ruq08937ZBZACek=
  - secure: TU9KI3phk22RCMMCPrSYQ7W3KY56MKJXLs0+ajYXunvP93OKOMG6XUVkkoHjMH4cm9tSe4kH64PhET8GWxJbZw8U5+5F7GEiA490Dn4D2FpwxZI+W7v2M5g1hQeSQjXnWPVhmDvkDaUvkdt97k+qJe5wdsVFdiTB9vg3JLXLOyg=
  matrix:
  - BROWSER=firefox
  - REMOTE_ARG="--remote-url=http://${SAUCE_USERNAME}:${SAUCE_ACCESS_KEY}@ondemand.saucelabs.com:80/wd/hub" BROWSER=firefox
  - REMOTE_ARG="--remote-url=http://${SAUCE_USERNAME}:${SAUCE_ACCESS_KEY}@ondemand.saucelabs.com:80/wd/hub" BROWSER=chrome
python:
- '2.7'
install:
- echo $SAUCE_USERNAME
- echo $SAUCE_ACCESS_KEY | cut -c1-9
  # install the project's requirements
- python setup.py install
  #  # install the selenium server for tests running with firefox
  #- if [ -n "$REMOTE_ARG" ]; then wget http://selenium-release.storage.googleapis.com/2.43/selenium-server-standalone-2.43.1.jar
  #  -O selenium-server.jar; fi
  #before_script:
  #  # Setup headless X per http://about.travis-ci.org/docs/user/gui-and-headless-browsers/
  #- export DISPLAY=:99.0
  #- sh -e /etc/init.d/xvfb start
  #- if [ -n "$REMOTE_ARG" ]; then (java -jar selenium-server.jar > /dev/null &); fi
  #- if [ -n "$REMOTE_ARG" ]; then sleep 60; fi
  # Start sauce connect tunnel
- if [ -n "$REMOTE_ARG" ]; then ./sauce_connect_setup.sh; fi
script:
- if [[ ! -n "$REMOTE" && $BROWSER == "firefox" ]]; then salad --browser=$BROWSER salad/not_remote_features/steps-browser-drag.feature; fi
- if [[ -n "$REMOTE" && $BROWSER == "firefox" ]]; then salad --browser=$BROWSER $REMOTE_ARG salad/features/; fi
- if [[ -n "$REMOTE" && $BROWSER == "chrome" ]]; then aslflsaj; fi
  #  https://code.google.com/p/chromedriver/issues/detail?id=467
