# chrome does not work on travis at the moment
# https://github.com/travis-ci/travis-ci/issues/938
language: python
env:
  matrix:
    - BROWSER=firefox
    - REMOTE_ARG='--remote-url=http://127.0.0.1:4444/wd/hub' BROWSER=firefox
python:
  - "2.6"
  - "2.7"
  #- "3.2" # Fails miserably in Python 3
install:
  - "python setup.py install"
  # Install the Selenium Server
  - 'if [ -n "$REMOTE_ARG" ]; then wget http://selenium-release.storage.googleapis.com/2.43/selenium-server-standalone-2.43.1.jar -O selenium-server.jar; fi'

before_script:
  # Setup headless X per http://about.travis-ci.org/docs/user/gui-and-headless-browsers/
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - 'if [ -n "$REMOTE_ARG" ]; then (java -jar selenium-server.jar > /dev/null &); fi'
  - 'if [ -n "$REMOTE_ARG" ]; then sleep 60; fi'
script:
  - 'if [[ ! -n "$REMOTE_ARG" ]]; then salad --browser=$BROWSER salad/not_remote_features/steps-browser-drag.feature --verbosity=2; fi'
  - "salad --browser=$BROWSER $REMOTE_ARG salad/features/ --verbosity=2"
